vich_uploader:
    db_driver: orm

    mappings:
        thumbnails:
            uri_prefix: /uploads/images/thumbnails
            upload_destination: '%kernel.project_dir%/public/uploads/images/thumbnails'
            #uri_prefix: '%app.path.thumbnails%'
            #upload_destination: '%kernel.project_dir%/public/%app.path.thumbnails%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
